# $Id: META.yml,v 1.1 2004/12/23 12:02:30 jminieri Exp $
# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SDEE
version:      0.01
version_from: lib/Net/SDEE.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
